// <auto-generated />
using System;
using GED_APP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GED_APP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GED_APP.Models._Arrete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateSign")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .HasColumnType("longtext");

                    b.Property<string>("Signataire")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("_Arretes");
                });

            modelBuilder.Entity("GED_APP.Models._Attestation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateSign")
                        .HasColumnType("longtext");

                    b.Property<string>("Destinataire")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Signataire")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("_Attestations");
                });

            modelBuilder.Entity("GED_APP.Models._Certificat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateSign")
                        .HasColumnType("longtext");

                    b.Property<string>("Destinataire")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Signataire")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("_Certificats");
                });

            modelBuilder.Entity("GED_APP.Models._Communique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateSign")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .HasColumnType("longtext");

                    b.Property<string>("Signataire")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("_Communiques");
                });

            modelBuilder.Entity("GED_APP.Models._Contrat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Beneficiaire")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateSign")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Signataire")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("_Contrats");
                });

            modelBuilder.Entity("GED_APP.Models._Correspondance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateSign")
                        .HasColumnType("longtext");

                    b.Property<string>("Emetteur")
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .HasColumnType("longtext");

                    b.Property<string>("Recepteur")
                        .HasColumnType("longtext");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.Property<string>("Signataire")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("_Correspondances");
                });

            modelBuilder.Entity("GED_APP.Models._Decision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateSign")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .HasColumnType("longtext");

                    b.Property<string>("Signataire")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("_Decisions");
                });

            modelBuilder.Entity("GED_APP.Models._Decret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateSign")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .HasColumnType("longtext");

                    b.Property<string>("Signataire")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("_Decrets");
                });

            modelBuilder.Entity("GED_APP.Models._EtatPaiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateSign")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .HasColumnType("longtext");

                    b.Property<string>("Signataire")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("_EtatPaiements");
                });

            modelBuilder.Entity("GED_APP.Models._NoteService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateSign")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .HasColumnType("longtext");

                    b.Property<string>("Signataire")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("_NoteServices");
                });

            modelBuilder.Entity("GED_APP.Models.Arrete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateCne")
                        .HasColumnType("longtext");

                    b.Property<string>("DateSign")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroCNE")
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .HasColumnType("longtext");

                    b.Property<string>("Origine")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StructureId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StructureId");

                    b.ToTable("Arretes");
                });

            modelBuilder.Entity("GED_APP.Models.Chronogramme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Annee")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Libele")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroPTA")
                        .HasColumnType("longtext");

                    b.Property<string>("Origine")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StructureId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StructureId");

                    b.ToTable("Chronogrammes");
                });

            modelBuilder.Entity("GED_APP.Models.Correspondance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Date")
                        .HasColumnType("longtext");

                    b.Property<string>("Initiateur")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .HasColumnType("longtext");

                    b.Property<string>("Origine")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StructureId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StructureId");

                    b.ToTable("Correspondances");
                });

            modelBuilder.Entity("GED_APP.Models.Cycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Libele")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Cycles");
                });

            modelBuilder.Entity("GED_APP.Models.Decharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Date")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Origine")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StructureId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StructureId");

                    b.ToTable("Decharges");
                });

            modelBuilder.Entity("GED_APP.Models.Doc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnneeAcademique")
                        .HasColumnType("longtext");

                    b.Property<string>("AnneeSortie")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CycleId")
                        .HasColumnType("int");

                    b.Property<string>("DateSign")
                        .HasColumnType("longtext");

                    b.Property<int?>("Fichier")
                        .HasColumnType("int");

                    b.Property<int?>("FiliereId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .HasColumnType("longtext");

                    b.Property<string>("Promotion")
                        .HasColumnType("longtext");

                    b.Property<string>("Session")
                        .HasColumnType("longtext");

                    b.Property<string>("Signataire")
                        .HasColumnType("longtext");

                    b.Property<string>("Source")
                        .HasColumnType("longtext");

                    b.Property<string>("TypeDoc")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.HasIndex("FiliereId");

                    b.ToTable("Docs");
                });

            modelBuilder.Entity("GED_APP.Models.Dossier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateEntree")
                        .HasColumnType("longtext");

                    b.Property<string>("DateSortie")
                        .HasColumnType("longtext");

                    b.Property<string>("Demandeur")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .HasColumnType("longtext");

                    b.Property<string>("Origine")
                        .HasColumnType("longtext");

                    b.Property<string>("PersonneTraite")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StructureId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StructureId");

                    b.ToTable("Dossiers");
                });

            modelBuilder.Entity("GED_APP.Models.Examen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nom")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Examens");
                });

            modelBuilder.Entity("GED_APP.Models.Faculte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Libele")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Facultes");
                });

            modelBuilder.Entity("GED_APP.Models.Filiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Libele")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("GED_APP.Models.Filieree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Filierees");
                });

            modelBuilder.Entity("GED_APP.Models.Liste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateCne")
                        .HasColumnType("longtext");

                    b.Property<string>("DateSign")
                        .HasColumnType("longtext");

                    b.Property<string>("Descritpion")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroCne")
                        .HasColumnType("longtext");

                    b.Property<string>("Origine")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StructureId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StructureId");

                    b.ToTable("Listes");
                });

            modelBuilder.Entity("GED_APP.Models.PvCNE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateCne")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroCne")
                        .HasColumnType("longtext");

                    b.Property<string>("Origine")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StructureId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StructureId");

                    b.ToTable("PvCNEs");
                });

            modelBuilder.Entity("GED_APP.Models.PvExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExamenId")
                        .HasColumnType("int");

                    b.Property<int?>("FaculteId")
                        .HasColumnType("int");

                    b.Property<int?>("FiliereId")
                        .HasColumnType("int");

                    b.Property<string>("Session")
                        .HasColumnType("longtext");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StructureId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ExamenId");

                    b.HasIndex("FaculteId");

                    b.HasIndex("FiliereId");

                    b.HasIndex("SourceId");

                    b.HasIndex("StructureId");

                    b.ToTable("PvExamens");
                });

            modelBuilder.Entity("GED_APP.Models.Rapport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Debut")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Fin")
                        .HasColumnType("longtext");

                    b.Property<string>("Origine")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StructureId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StructureId");

                    b.ToTable("Rapports");
                });

            modelBuilder.Entity("GED_APP.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Libele")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("GED_APP.Models.Structure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Libele")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Structures");
                });

            modelBuilder.Entity("GED_APP.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("KeepLoginIn")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<string>("SaltPassword")
                        .HasColumnType("longtext");

                    b.Property<string>("Service")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<string>("UserEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GED_APP.Models.Arrete", b =>
                {
                    b.HasOne("GED_APP.Models.Structure", "Structure")
                        .WithMany("Arretes")
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("GED_APP.Models.Chronogramme", b =>
                {
                    b.HasOne("GED_APP.Models.Structure", "Structure")
                        .WithMany("Chronos")
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("GED_APP.Models.Correspondance", b =>
                {
                    b.HasOne("GED_APP.Models.Structure", "Structure")
                        .WithMany("Correspondances")
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("GED_APP.Models.Decharge", b =>
                {
                    b.HasOne("GED_APP.Models.Structure", "Structure")
                        .WithMany("Decharges")
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("GED_APP.Models.Doc", b =>
                {
                    b.HasOne("GED_APP.Models.Cycle", "Cycle")
                        .WithMany("Documents")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GED_APP.Models.Filiere", "Filiere")
                        .WithMany("Documents")
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cycle");

                    b.Navigation("Filiere");
                });

            modelBuilder.Entity("GED_APP.Models.Dossier", b =>
                {
                    b.HasOne("GED_APP.Models.Structure", "Structure")
                        .WithMany("Dossiers")
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("GED_APP.Models.Liste", b =>
                {
                    b.HasOne("GED_APP.Models.Structure", "Structure")
                        .WithMany("Listes")
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("GED_APP.Models.PvCNE", b =>
                {
                    b.HasOne("GED_APP.Models.Structure", "Structure")
                        .WithMany("PvCNEs")
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("GED_APP.Models.PvExamen", b =>
                {
                    b.HasOne("GED_APP.Models.Examen", "Examen")
                        .WithMany("Pvs")
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GED_APP.Models.Faculte", "Faculte")
                        .WithMany("PvExamens")
                        .HasForeignKey("FaculteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GED_APP.Models.Filieree", "Filiere")
                        .WithMany("PvExamens")
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GED_APP.Models.Source", "Source")
                        .WithMany("PvExamens")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GED_APP.Models.Structure", "Structure")
                        .WithMany("PvExamens")
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Examen");

                    b.Navigation("Faculte");

                    b.Navigation("Filiere");

                    b.Navigation("Source");

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("GED_APP.Models.Rapport", b =>
                {
                    b.HasOne("GED_APP.Models.Structure", "Structure")
                        .WithMany("Rapports")
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("GED_APP.Models.Cycle", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("GED_APP.Models.Examen", b =>
                {
                    b.Navigation("Pvs");
                });

            modelBuilder.Entity("GED_APP.Models.Faculte", b =>
                {
                    b.Navigation("PvExamens");
                });

            modelBuilder.Entity("GED_APP.Models.Filiere", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("GED_APP.Models.Filieree", b =>
                {
                    b.Navigation("PvExamens");
                });

            modelBuilder.Entity("GED_APP.Models.Source", b =>
                {
                    b.Navigation("PvExamens");
                });

            modelBuilder.Entity("GED_APP.Models.Structure", b =>
                {
                    b.Navigation("Arretes");

                    b.Navigation("Chronos");

                    b.Navigation("Correspondances");

                    b.Navigation("Decharges");

                    b.Navigation("Dossiers");

                    b.Navigation("Listes");

                    b.Navigation("PvCNEs");

                    b.Navigation("PvExamens");

                    b.Navigation("Rapports");
                });
#pragma warning restore 612, 618
        }
    }
}
